var data_AS3600Variables={"prettyheader":["ID","Prerequisite","Name","Description","Notation","UNICODE","Value","Unit","Assumable"],"header":["id","prereq","name","description","notation","unicode","value","unit","assumable"],"data":[["Ag","!Ag&B&D","Gross sectional area","gross cross-sectional area of a member","A_g","A_g","","mm\u00b2",""],["As","!As","Area of reinforcement","cross-sectional area of reinforcement (see Clauses 3.4.3.2 and 13.2.2);","A_s","A_s","","mm\u00b2",""],["Asc","!Asc","Area of compressive steel",
"cross-sectional area of compressive reinforcement","A_{sc}","A_sc","","mm\u00b2",""],["Ast","!Ast","Area of tensile steel","cross-sectional area of longitudinal tensile reinforcement; or cross-sectional area of reinforcement in the zone that would be in tension under the design loads if the effects of prestress and axial loads are ignored","A_{st}","A_st","","mm\u00b2","yes"],["B","!B","Breadth of beam","width of a rectangular cross-section or member","b","b","","mm","yes"],["bt","!bt","Beam type",
"","\\text{Beam Type}","Beam Type","t","","no"],["Cc","!Cc&dn","Concrete Compression","","C_c","C_c","","kN","no"],["cchk","!cchk&phi&mstar&muo","Capacity Check","","\\text{Capacity Check}","Capacity Check","","","no"],["d","!d&D","Depth to tensile steel centroid","effective depth of a cross-section in the plane of bending","d","d","","mm","yes"],["D","!D","Depth of beam","overall depth of a cross-section in the plane of bending; or depth or breadth of the symmetrical prism as appropriate (see Clause 12.5.6)",
"D","D","","mm","yes"],["dn","!dn&alphatwo&fc&gamma&B&fsy&Ast","Depth to neutral axis","","d_n","d_n","","mm","yes"],["Ec","!Ec","Concrete modulus of elasticity","mean value of the modulus of elasticity of concrete at 28 days","E_c","E_c","","GPa",""],["fsy","!fsy","Steel characteristic yield strength","characteristic yield strength of reinforcement (referred to as Re in AS/NZS 4671), determined in accordance with Clause 3.2.1","f_{sy}","f_sy",500,"MPa","yes"],["fc","!fc","Concrete characteristic strength",
"characteristic compressive (cylinder) strength of concrete at 28 days","f'_{c}","f'_c","","MPa","yes"],["fctf","!fctf&fc","Concrete characteristic tensile strength","measured flexural tensile strength of concrete (see Clause 3.1.1.3)","f'_{ct.f}","f'_ct.f","","MPa","no"],["I","!I&B&D","Second moment of area","second moment of area of the uncracked concrete cross-section about the centroidal axis","I","I","","mm\u2074","no"],["Icr","!Icr","Transformed area second moment of area","second moment of area of a cracked section with the reinforcement transformed to an equivalent area of concrete",
"I_{cr}","I_cr","","mm\u2074",""],["Ief","!Ief","Effective second moment of area","an effective second moment of area (see Clause 8.5.3)","I_{ef}","I_ef","","mm\u2074",""],["Iefmax","!Iefmax","Maximum effective second moment of area","maximum effective second moment of area (see Clause 8.5.3)","I_{ef.max}","I_ef.max","","mm\u2074",""],["ku","!ku&d&dn","k_u ratio","neutral axis parameter being the ratio, at ultimate strength under any combination of bending and compression, of the depth to the neutral axis from the extreme compressive fibre to d",
"k_u","k_u","","","no"],["muo","!muo&Cc&Ts&dn&gamma","Moment capacity","ultimate strength in bending, without axial force, at a cross-section","M_{uo}","M_ou","","kN\u22c5m","no"],["muomin","!muomin&Z&fctf","Minimum design capacity","minimum required strength in bending at a critical cross-section (see Clause 8.1.6.1)","(M_{uo})_{min}","M_ou_min","","kN\u22c5m","no"],["mstar","!mstar","Moment design capacity","design bending moment at a cross-section","M^*","M*","","kN\u22c5m","yes"],["Ts","!Ts&Ast&fsy",
"Force in tensile steel","","T_s","T_s","","kN","no"],["Z","!Z&I","Section modulus","section modulus of the uncracked cross-section, referred to the extreme fibre at which flexural cracking occurs (see Clause 8.1.6.1)","Z","Z","","mm\u00b3","no"],["alphatwo","!alphatwo","Alpha2 Coefficient",'Coefficient of concrete compressive area in the "Equivalent compression block method"',"\\alpha_2","\u03b1\u2082","","","no"],["gamma","!gamma&fc","Gamma Ratio","the ratio, under design bending or design combined bending and compression, of the depth of the assumed rectangular compressive stress block to k_u * d",
"\\gamma","\u03a5","","","no"],["phi","!phi","Capacity reduction factor","capacity reduction factor for design using linear elastic analysis (see Clause 2.2.2)","\\Phi","\u03a6","","","yes"]]};var TAFFY,exports,T;
(function(){var f,q,p,t,d,b,n,m,r,e,c,u,w,v,h,g,j,o,i,l,a,s,k;if(!TAFFY){d="2.7";b=1;n="000000";m=1E3;r={};e=function(x){if(TAFFY.isArray(x)||TAFFY.isObject(x))return x;else return JSON.parse(x)};i=function(y,x){return l(y,function(z){return x.indexOf(z)>=0})};l=function(A,z,y){var x=[];if(A==null)return x;if(Array.prototype.filter&&A.filter===Array.prototype.filter)return A.filter(z,y);c(A,function(D,B,C){if(z.call(y,D,B,C))x[x.length]=D});return x};k=function(x){return Object.prototype.toString.call(x)===
"[object RegExp]"};s=function(z){var x=T.isArray(z)?[]:T.isObject(z)?{}:null;if(z===null)return z;for(var y in z)x[y]=k(z[y])?z[y].toString():T.isArray(z[y])||T.isObject(z[y])?s(z[y]):z[y];return x};a=function(y){var x=JSON.stringify(y);if(x.match(/regex/)===null)return x;return JSON.stringify(s(y))};c=function(B,A,C){var E,D,z,F;if(B&&(T.isArray(B)&&B.length===1||!T.isArray(B)))A(T.isArray(B)?B[0]:B,0);else for(E,D,z=0,B=T.isArray(B)?B:[B],F=B.length;z<F;z++){D=B[z];if(!T.isUndefined(D)||(C||false)){E=
A(D,z);if(E===T.EXIT)break}}};u=function(C,z){var y=0,B,A;for(A in C)if(C.hasOwnProperty(A)){B=z(C[A],A,y++);if(B===T.EXIT)break}};r.extend=function(x,y){r[x]=function(){return y.apply(this,arguments)}};w=function(y){var x;if(T.isString(y)&&/[t][0-9]*[r][0-9]*/i.test(y))return true;if(T.isObject(y)&&(y.___id&&y.___s))return true;if(T.isArray(y)){x=true;c(y,function(z){if(!w(z)){x=false;return TAFFY.EXIT}});return x}return false};h=function(z,y){var x=true;c(y,function(A){switch(T.typeOf(A)){case "function":if(!A.apply(z)){x=
false;return TAFFY.EXIT}break;case "array":x=A.length===1?h(z,A[0]):A.length===2?h(z,A[0])||h(z,A[1]):A.length===3?h(z,A[0])||(h(z,A[1])||h(z,A[2])):A.length===4?h(z,A[0])||(h(z,A[1])||(h(z,A[2])||h(z,A[3]))):false;if(A.length>4)c(A,function(B){if(h(z,B))x=true});break}});return x};v=function(y){var x=[];if(T.isString(y)&&/[t][0-9]*[r][0-9]*/i.test(y))y={___id:y};if(T.isArray(y)){c(y,function(z){x.push(v(z))});y=function(){var A=this,z=false;c(x,function(B){if(h(A,B))z=true});return z};return y}if(T.isObject(y)){if(T.isObject(y)&&
(y.___id&&y.___s))y={___id:y.___id};u(y,function(z,A){if(!T.isObject(z))z={is:z};u(z,function(B,C){var E=[],D;D=C==="hasAll"?function(F,G){G(F)}:c;D(B,function(G){var F=true,H=false,I;I=function(){var N=this[A],M="==",O="!=",Q="===",R="<",L=">",S="<=",P=">=",K="!==",J;if(typeof N==="undefined")return false;if(C.indexOf("!")===0&&(C!==O&&C!==K)){F=false;C=C.substring(1,C.length)}J=C==="regex"?G.test(N):C==="lt"||C===R?N<G:C==="gt"||C===L?N>G:C==="lte"||C===S?N<=G:C==="gte"||C===P?N>=G:C==="left"?N.indexOf(G)===
0:C==="leftnocase"?N.toLowerCase().indexOf(G.toLowerCase())===0:C==="right"?N.substring(N.length-G.length)===G:C==="rightnocase"?N.toLowerCase().substring(N.length-G.length)===G.toLowerCase():C==="like"?N.indexOf(G)>=0:C==="likenocase"?N.toLowerCase().indexOf(G.toLowerCase())>=0:C===Q||C==="is"?N===G:C===M?N==G:C===K?N!==G:C===O?N!=G:C==="isnocase"?N.toLowerCase?N.toLowerCase()===G.toLowerCase():N===G:C==="has"?T.has(N,G):C==="hasall"?T.hasAll(N,G):C==="contains"?TAFFY.isArray(N)&&N.indexOf(G)>-1:
C.indexOf("is")===-1&&(!TAFFY.isNull(N)&&(!TAFFY.isUndefined(N)&&(!TAFFY.isObject(G)&&!TAFFY.isArray(G))))?G===N[C]:T[C]&&(T.isFunction(T[C])&&C.indexOf("is")===0)?T[C](N)===G:T[C]&&T.isFunction(T[C])?T[C](N,G):false;J=J&&!F?false:!J&&!F?true:J;return J};E.push(I)});if(E.length===1)x.push(E[0]);else x.push(function(){var G=this,F=false;c(E,function(H){if(H.apply(G))F=true});return F})})});y=function(){var A=this,z=true;z=x.length===1&&!x[0].apply(A)?false:x.length===2&&(!x[0].apply(A)||!x[1].apply(A))?
false:x.length===3&&(!x[0].apply(A)||(!x[1].apply(A)||!x[2].apply(A)))?false:x.length===4&&(!x[0].apply(A)||(!x[1].apply(A)||(!x[2].apply(A)||!x[3].apply(A))))?false:true;if(x.length>4)c(x,function(B){if(!h(A,B))z=false});return z};return y}if(T.isFunction(y))return y};j=function(x,y){var z=function(B,A){var C=0;T.each(y,function(F){var H,E,D,I,G;H=F.split(" ");E=H[0];D=H.length===1?"logical":H[1];if(D==="logical"){I=g(B[E]);G=g(A[E]);T.each(I.length<=G.length?I:G,function(J,K){if(I[K]<G[K]){C=-1;
return TAFFY.EXIT}else if(I[K]>G[K]){C=1;return TAFFY.EXIT}})}else if(D==="logicaldesc"){I=g(B[E]);G=g(A[E]);T.each(I.length<=G.length?I:G,function(J,K){if(I[K]>G[K]){C=-1;return TAFFY.EXIT}else if(I[K]<G[K]){C=1;return TAFFY.EXIT}})}else if(D==="asec"&&B[E]<A[E]){C=-1;return T.EXIT}else if(D==="asec"&&B[E]>A[E]){C=1;return T.EXIT}else if(D==="desc"&&B[E]>A[E]){C=-1;return T.EXIT}else if(D==="desc"&&B[E]<A[E]){C=1;return T.EXIT}if(C===0&&(D==="logical"&&I.length<G.length))C=-1;else if(C===0&&(D===
"logical"&&I.length>G.length))C=1;else if(C===0&&(D==="logicaldesc"&&I.length>G.length))C=-1;else if(C===0&&(D==="logicaldesc"&&I.length<G.length))C=1;if(C!==0)return T.EXIT});return C};return x&&x.push?x.sort(z):x};(function(){var x={},y=0;g=function(z){if(y>m){x={};y=0}return x["_"+z]||function(){var D=String(z),C=[],G="_",B="",A,E,F;for(A=0,E=D.length;A<E;A++){F=D.charCodeAt(A);if(F>=48&&F<=57||F===46){if(B!=="n"){B="n";C.push(G.toLowerCase());G=""}G=G+D.charAt(A)}else{if(B!=="s"){B="s";C.push(parseFloat(G));
G=""}G=G+D.charAt(A)}}C.push(B==="n"?parseFloat(G):G.toLowerCase());C.shift();x["_"+z]=C;y++;return C}()}})();o=function(){this.context({results:this.getDBI().query(this.context())})};r.extend("filter",function(){var y=TAFFY.mergeObj(this.context(),{run:null}),x=[];c(y.q,function(z){x.push(z)});y.q=x;c(arguments,function(z){y.q.push(v(z));y.filterRaw.push(z)});return this.getroot(y)});r.extend("order",function(z){z=z.split(",");var y=[],A;c(z,function(x){y.push(x.replace(/^\s*/,"").replace(/\s*$/,
""))});A=TAFFY.mergeObj(this.context(),{sort:null});A.order=y;return this.getroot(A)});r.extend("limit",function(z){var y=TAFFY.mergeObj(this.context(),{}),x;y.limit=z;if(y.run&&y.sort){x=[];c(y.results,function(B,A){if(A+1>z)return TAFFY.EXIT;x.push(B)});y.results=x}return this.getroot(y)});r.extend("start",function(z){var y=TAFFY.mergeObj(this.context(),{}),x;y.start=z;if(y.run&&(y.sort&&!y.limit)){x=[];c(y.results,function(B,A){if(A+1>z)x.push(B)});y.results=x}else y=TAFFY.mergeObj(this.context(),
{run:null,start:z});return this.getroot(y)});r.extend("update",function(A,z,x){var B=true,D={},y=arguments,C;if(TAFFY.isString(A)&&(arguments.length===2||arguments.length===3)){D[A]=z;if(arguments.length===3)B=x}else{D=A;if(y.length===2)B=z}C=this;o.call(this);c(this.context().results,function(E){var F=D;if(TAFFY.isFunction(F))F=F.apply(TAFFY.mergeObj(E,{}));else if(T.isFunction(F))F=F(TAFFY.mergeObj(E,{}));if(TAFFY.isObject(F))C.getDBI().update(E.___id,F,B)});if(this.context().results.length)this.context({run:null});
return this});r.extend("remove",function(x){var y=this,z=0;o.call(this);c(this.context().results,function(A){y.getDBI().remove(A.___id);z++});if(this.context().results.length){this.context({run:null});y.getDBI().removeCommit(x)}return z});r.extend("count",function(){o.call(this);return this.context().results.length});r.extend("callback",function(z,x){if(z){var y=this;setTimeout(function(){o.call(y);z.call(y.getroot(y.context()))},x||0)}return null});r.extend("get",function(){o.call(this);return this.context().results});
r.extend("stringify",function(){return JSON.stringify(this.get())});r.extend("first",function(){o.call(this);return this.context().results[0]||false});r.extend("last",function(){o.call(this);return this.context().results[this.context().results.length-1]||false});r.extend("sum",function(){var y=0,x=this;o.call(x);c(arguments,function(z){c(x.context().results,function(A){y=y+(A[z]||0)})});return y});r.extend("min",function(y){var x=null;o.call(this);c(this.context().results,function(z){if(x===null||
z[y]<x)x=z[y]});return x});(function(){var x=function(){var A,y,z;A=function(E,G,D){var C,F,H,B;if(D.length===2){C=E[D[0]];H="===";F=G[D[1]]}else{C=E[D[0]];H=D[1];F=G[D[2]]}switch(H){case "===":return C===F;case "!==":return C!==F;case "<":return C<F;case ">":return C>F;case "<=":return C<=F;case ">=":return C>=F;case "==":return C==F;case "!=":return C!=F;default:throw String(H)+" is not supported";}};y=function(C,F){var B={},D,E;for(D in C)if(C.hasOwnProperty(D))B[D]=C[D];for(D in F)if(F.hasOwnProperty(D)&&
(D!=="___id"&&D!=="___s")){E=!TAFFY.isUndefined(B[D])?"right_":"";B[E+String(D)]=F[D]}return B};z=function(F){var B,D,C=arguments,E=C.length,G=[];if(typeof F.filter!=="function")if(F.TAFFY)B=F();else throw"TAFFY DB or result not supplied";else B=F;this.context({results:this.getDBI().query(this.context())});TAFFY.each(this.context().results,function(H){B.each(function(K){var I,J=true;CONDITION:for(D=1;D<E;D++){I=C[D];if(typeof I==="function")J=I(H,K);else if(typeof I==="object"&&I.length)J=A(H,K,I);
else J=false;if(!J)break CONDITION}if(J)G.push(y(H,K))})});return TAFFY(G)()};return z}();r.extend("join",x)})();r.extend("max",function(y){var x=null;o.call(this);c(this.context().results,function(z){if(x===null||z[y]>x)x=z[y]});return x});r.extend("select",function(){var y=[],x=arguments;o.call(this);if(arguments.length===1)c(this.context().results,function(z){y.push(z[x[0]])});else c(this.context().results,function(z){var A=[];c(x,function(B){A.push(z[B])});y.push(A)});return y});r.extend("distinct",
function(){var y=[],x=arguments;o.call(this);if(arguments.length===1)c(this.context().results,function(A){var z=A[x[0]],B=false;c(y,function(C){if(z===C){B=true;return TAFFY.EXIT}});if(!B)y.push(z)});else c(this.context().results,function(z){var B=[],A=false;c(x,function(C){B.push(z[C])});c(y,function(D){var C=true;c(x,function(F,E){if(B[E]!==D[E]){C=false;return TAFFY.EXIT}});if(C){A=true;return TAFFY.EXIT}});if(!A)y.push(B)});return y});r.extend("supplant",function(y,x){var z=[];o.call(this);c(this.context().results,
function(A){z.push(y.replace(/\{([^\{\}]*)\}/g,function(C,B){var D=A[B];return typeof D==="string"||typeof D==="number"?D:C}))});return!x?z.join(""):z});r.extend("each",function(x){o.call(this);c(this.context().results,x);return this});r.extend("map",function(x){var y=[];o.call(this);c(this.context().results,function(z){y.push(x(z))});return y});T=function(F){var C=[],G={},D=1,z={template:false,onInsert:false,onUpdate:false,onRemove:false,onDBChange:false,storageName:false,forcePropertyCase:null,
cacheSize:100,name:""},B=new Date,A=0,y=0,I={},E,x,H;x=function(L){var K=[],J=false;if(L.length===0)return C;c(L,function(M){if(T.isString(M)&&(/[t][0-9]*[r][0-9]*/i.test(M)&&C[G[M]])){K.push(C[G[M]]);J=true}if(T.isObject(M)&&(M.___id&&(M.___s&&C[G[M.___id]]))){K.push(C[G[M.___id]]);J=true}if(T.isArray(M))c(M,function(N){c(x(N),function(O){K.push(O)})})});if(J&&K.length>1)K=[];return K};E={dm:function(J){if(J){B=J;I={};A=0;y=0}if(z.onDBChange)setTimeout(function(){z.onDBChange.call(C)},0);if(z.storageName)setTimeout(function(){localStorage.setItem("taffy_"+
z.storageName,JSON.stringify(C))});return B},insert:function(M,N){var L=[],K=[],J=e(M);c(J,function(P,Q){var O,R;if(T.isArray(P)&&Q===0){c(P,function(S){L.push(z.forcePropertyCase==="lower"?S.toLowerCase():z.forcePropertyCase==="upper"?S.toUpperCase():S)});return true}else if(T.isArray(P)){O={};c(P,function(U,S){O[L[S]]=U});P=O}else if(T.isObject(P)&&z.forcePropertyCase){R={};u(P,function(U,S){R[z.forcePropertyCase==="lower"?S.toLowerCase():z.forcePropertyCase==="upper"?S.toUpperCase():S]=P[S]});
P=R}D++;P.___id="T"+String(n+b).slice(-6)+"R"+String(n+D).slice(-6);P.___s=true;K.push(P.___id);if(z.template)P=T.mergeObj(z.template,P);C.push(P);G[P.___id]=C.length-1;if(z.onInsert&&(N||TAFFY.isUndefined(N)))z.onInsert.call(P);E.dm(new Date)});return H(K)},sort:function(J){C=j(C,J.split(","));G={};c(C,function(L,K){G[L.___id]=K});E.dm(new Date);return true},update:function(Q,M,L){var P={},O,N,J,K;if(z.forcePropertyCase){u(M,function(R,S){P[z.forcePropertyCase==="lower"?S.toLowerCase():z.forcePropertyCase===
"upper"?S.toUpperCase():S]=R});M=P}O=C[G[Q]];N=T.mergeObj(O,M);J={};K=false;u(N,function(R,S){if(TAFFY.isUndefined(O[S])||O[S]!==R){J[S]=R;K=true}});if(K){if(z.onUpdate&&(L||TAFFY.isUndefined(L)))z.onUpdate.call(N,C[G[Q]],J);C[G[Q]]=N;E.dm(new Date)}},remove:function(J){C[G[J]].___s=false},removeCommit:function(K){var J;for(J=C.length-1;J>-1;J--)if(!C[J].___s){if(z.onRemove&&(K||TAFFY.isUndefined(K)))z.onRemove.call(C[J]);G[C[J].___id]=undefined;C.splice(J,1)}G={};c(C,function(M,L){G[M.___id]=L});
E.dm(new Date)},query:function(L){var O,P,K,N,M,J;if(z.cacheSize){P="";c(L.filterRaw,function(Q){if(T.isFunction(Q)){P="nocache";return TAFFY.EXIT}});if(P==="")P=a(T.mergeObj(L,{q:false,run:false,sort:false}))}if(!L.results||(!L.run||L.run&&E.dm()>L.run)){K=[];if(z.cacheSize&&I[P]){I[P].i=A++;return I[P].results}else if(L.q.length===0&&L.index.length===0){c(C,function(Q){K.push(Q)});O=K}else{N=x(L.index);c(N,function(Q){if(L.q.length===0||h(Q,L.q))K.push(Q)});O=K}}else O=L.results;if(L.order.length>
0&&(!L.run||!L.sort))O=j(O,L.order);if(O.length&&(L.limit&&L.limit<O.length||L.start)){M=[];c(O,function(R,Q){if(!L.start||L.start&&Q+1>=L.start)if(L.limit){J=L.start?Q+1-L.start:Q;if(J<L.limit)M.push(R);else if(J>L.limit)return TAFFY.EXIT}else M.push(R)});O=M}if(z.cacheSize&&P!=="nocache"){y++;setTimeout(function(){var Q,R;if(y>=z.cacheSize*2){y=0;Q=A-z.cacheSize;R={};u(function(U,S){if(U.i>=Q)R[S]=U});I=R}},0);I[P]={i:A++,results:O}}return O}};H=function(){var K,J;K=TAFFY.mergeObj(TAFFY.mergeObj(r,
{insert:undefined}),{getDBI:function(){return E},getroot:function(L){return H.call(L)},context:function(L){if(L)J=TAFFY.mergeObj(J,L.hasOwnProperty("results")?TAFFY.mergeObj(L,{run:new Date,sort:new Date}):L);return J},extend:undefined});J=this&&this.q?this:{limit:false,start:false,q:[],filterRaw:[],index:[],order:[],results:false,run:null,sort:null,settings:z};c(arguments,function(L){if(w(L))J.index.push(L);else J.q.push(v(L));J.filterRaw.push(L)});return K};b++;if(F)E.insert(F);H.insert=E.insert;
H.merge=function(M,L,N){var K={},J=[],O={};N=N||false;L=L||"id";c(M,function(Q){var P;K[L]=Q[L];J.push(Q[L]);P=H(K).first();if(P)E.update(P.___id,Q,N);else E.insert(Q,N)});O[L]=J;return H(O)};H.TAFFY=true;H.sort=E.sort;H.settings=function(J){if(J){z=TAFFY.mergeObj(z,J);if(J.template)H().update(J.template)}return z};H.store=function(L){var K=false,J;if(localStorage){if(L){J=localStorage.getItem("taffy_"+L);if(J&&J.length>0){H.insert(J);K=true}if(C.length>0)setTimeout(function(){localStorage.setItem("taffy_"+
z.storageName,JSON.stringify(C))})}H.settings({storageName:L})}return H};return H};TAFFY=T;T.each=c;T.eachin=u;T.extend=r.extend;TAFFY.EXIT="TAFFYEXIT";TAFFY.mergeObj=function(z,x){var y={};u(z,function(A,B){y[B]=z[B]});u(x,function(A,B){y[B]=x[B]});return y};TAFFY.has=function(z,y){var x=false,A;if(z.TAFFY){x=z(y);if(x.length>0)return true;else return false}else switch(T.typeOf(z)){case "object":if(T.isObject(y))u(y,function(B,C){if(x===true&&(!T.isUndefined(z[C])&&z.hasOwnProperty(C)))x=T.has(z[C],
y[C]);else{x=false;return TAFFY.EXIT}});else if(T.isArray(y))c(y,function(B,C){x=T.has(z,y[C]);if(x)return TAFFY.EXIT});else if(T.isString(y))if(!TAFFY.isUndefined(z[y]))return true;else return false;return x;case "array":if(T.isObject(y))c(z,function(B,C){x=T.has(z[C],y);if(x===true)return TAFFY.EXIT});else if(T.isArray(y))c(y,function(C,B){c(z,function(E,D){x=T.has(z[D],y[B]);if(x===true)return TAFFY.EXIT});if(x===true)return TAFFY.EXIT});else if(T.isString(y)||T.isNumber(y)){x=false;for(A=0;A<
z.length;A++){x=T.has(z[A],y);if(x)return true}}return x;case "string":if(T.isString(y)&&y===z)return true;break;default:if(T.typeOf(z)===T.typeOf(y)&&z===y)return true;break}return false};TAFFY.hasAll=function(A,z){var y=TAFFY,x;if(y.isArray(z)){x=true;c(z,function(B){x=y.has(A,B);if(x===false)return TAFFY.EXIT});return x}else return y.has(A,z)};TAFFY.typeOf=function(x){var y=typeof x;if(y==="object")if(x){if(typeof x.length==="number"&&!x.propertyIsEnumerable("length"))y="array"}else y="null";return y};
TAFFY.getObjectKeys=function(x){var y=[];u(x,function(A,z){y.push(z)});y.sort();return y};TAFFY.isSameArray=function(y,x){return TAFFY.isArray(y)&&(TAFFY.isArray(x)&&y.join(",")===x.join(","))?true:false};TAFFY.isSameObject=function(A,y){var x=TAFFY,z=true;if(x.isObject(A)&&x.isObject(y))if(x.isSameArray(x.getObjectKeys(A),x.getObjectKeys(y)))u(A,function(B,C){if(!(x.isObject(A[C])&&(x.isObject(y[C])&&x.isSameObject(A[C],y[C]))||(x.isArray(A[C])&&(x.isArray(y[C])&&x.isSameArray(A[C],y[C]))||A[C]===
y[C]))){z=false;return TAFFY.EXIT}});else z=false;else z=false;return z};f=["String","Number","Object","Array","Boolean","Null","Function","Undefined"];q=function(x){return function(y){return TAFFY.typeOf(y)===x.toLowerCase()?true:false}};for(p=0;p<f.length;p++){t=f[p];TAFFY["is"+t]=q(t)}}})();if(typeof exports==="object")exports.taffy=TAFFY;
function Arimsys(database){this.dat=database;this.getAvaliable=function(){var i;var result=[];this.dat().each(function(r){if(r.prereq===""||this.checkPrerequisite(r.prereq))result.push(r.id)}.bind(this));return result}.bind(this);this.checkPrerequisite=function(str){var prereq=prereqpegjs.parse(str);return this.check(prereq)}.bind(this);this.check=function(exp){var funcname=exp.shift();return this[funcname].apply(this,exp)}.bind(this);this.has=function(varname){var val=this.dat({"id":varname}).first().value;
return val!==null&&(val!==undefined&&val!=="")}.bind(this);this.and=function(left,right){return this.check(left)&&this.check(right)};this.or=function(left,right){return this.check(left)||this.check(right)};this.not=function(right){return!this.check(right)}.bind(this);this.eq=function(left,right){var val=this.dat({"id":left}).first().value;return val==right}}
prereqpegjs=function(){function y(e){return'"'+e.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E-\x1F\x80-\uFFFF]/g,escape)+'"'}var n={parse:function(e,l){function h(a){b<q||(b>q&&(q=b,u=[]),u.push(a))}function v(){var a,c,d,g,f;f=g=b;a=p();null!==a?(124===e.charCodeAt(b)?(c="|",b++):(c=null,0===k&&h('"|"')),null!==c?(d=v(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):
(a=null,b=f);null!==a&&(a=["or",a[0],a[2]]);null===a&&(b=g);null===a&&(a=p());return a}function p(){var a,c,d,g,f;f=g=b;a=w();null!==a?(38===e.charCodeAt(b)?(c="&",b++):(c=null,0===k&&h('"&"')),null!==c?(d=p(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f);null!==a&&(a=["and",a[0],a[2]]);null===a&&(b=g);null===a&&(f=g=b,a=r(),null!==a?(61===e.charCodeAt(b)?(c="=",b++):(c=null,0===k&&h('"="')),null!==c?(d=s(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f),null!==a&&(a=["eq",
a[0],a[2]]),null===a&&(b=g),null===a&&(f=g=b,a=r(),null!==a?(61===e.charCodeAt(b)?(c="=",b++):(c=null,0===k&&h('"="')),null!==c?(d=t(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f),null!==a&&(a=["eq",a[0],a[2]]),null===a&&(b=g),null===a&&(f=g=b,a=s(),null!==a?(61===e.charCodeAt(b)?(c="=",b++):(c=null,0===k&&h('"="')),null!==c?(d=r(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f),null!==a&&(a=["eq",a[2],a[0]]),null===a&&(b=g),null===a&&(f=g=b,a=t(),null!==a?(61===e.charCodeAt(b)?
(c="=",b++):(c=null,0===k&&h('"="')),null!==c?(d=r(),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f),null!==a&&(a=["eq",a[2],a[0]]),null===a&&(b=g),null===a&&(a=w())))));return a}function w(){var a,c,d,g;g=d=b;33===e.charCodeAt(b)?(a="!",b++):(a=null,0===k&&h('"!"'));null!==a?(c=x(),null!==c?a=[a,c]:(a=null,b=g)):(a=null,b=g);null!==a&&(a=["not",a[1]]);null===a&&(b=d);null===a&&(a=x());return a}function x(){var a,c,d,g,f;a=n();null===a&&(a=t(),null===a&&(a=s(),null===a&&(f=g=b,40===e.charCodeAt(b)?
(a="(",b++):(a=null,0===k&&h('"("')),null!==a?(c=v(),null!==c?(41===e.charCodeAt(b)?(d=")",b++):(d=null,0===k&&h('")"')),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)):(a=null,b=f),null!==a&&(a=a[1]),null===a&&(b=g))));return a}function t(){var a,c,d;k++;d=b;/^[0-9.]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[0-9.]"));if(null!==c)for(a=[];null!==c;)a.push(c),/^[0-9.]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[0-9.]"));else a=null;null!==a&&(a=parseFloat(a.join("")));
null===a&&(b=d);k--;0===k&&(null===a&&h("number"));return a}function n(){var a,c,d;d=b;/^[a-zA-Z_]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[a-zA-Z_]"));if(null!==c)for(a=[];null!==c;)a.push(c),/^[a-zA-Z_]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[a-zA-Z_]"));else a=null;null!==a&&(a=["has",a.join("")]);null===a&&(b=d);return a}function r(){var a,c,d;d=b;/^[a-zA-Z_]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[a-zA-Z_]"));if(null!==c)for(a=[];null!==c;)a.push(c),
/^[a-zA-Z_]/.test(e.charAt(b))?(c=e.charAt(b),b++):(c=null,0===k&&h("[a-zA-Z_]"));else a=null;null!==a&&(a=a.join(""));null===a&&(b=d);return a}function s(){var a,c,d,g,f;f=g=b;34===e.charCodeAt(b)?(a='"',b++):(a=null,0===k&&h('"\\""'));if(null!==a){/^[^"]/.test(e.charAt(b))?(d=e.charAt(b),b++):(d=null,0===k&&h('[^"]'));if(null!==d)for(c=[];null!==d;)c.push(d),/^[^"]/.test(e.charAt(b))?(d=e.charAt(b),b++):(d=null,0===k&&h('[^"]'));else c=null;null!==c?(34===e.charCodeAt(b)?(d='"',b++):(d=null,0===
k&&h('"\\""')),null!==d?a=[a,c,d]:(a=null,b=f)):(a=null,b=f)}else a=null,b=f;null!==a&&(a=a[1].join(""));null===a&&(b=g);return a}function A(a){a.sort();for(var b=null,d=[],e=0;e<a.length;e++)a[e]!==b&&(d.push(a[e]),b=a[e]);return d}function B(){for(var a=1,c=1,d=!1,g=0;g<Math.max(b,q);g++){var f=e.charAt(g);"\n"===f?(d||a++,c=1,d=!1):"\r"===f||("\u2028"===f||"\u2029"===f)?(a++,c=1,d=!0):(c++,d=!1)}return{c:a,b:c}}var m={addi:v,multi:p,unary:w,primary:x,number:t,has:n,valueof:r,string:s};if(void 0!==
l){if(void 0===m[l])throw Error("Invalid rule name: "+y(l)+".");}else l="addi";var b=0,k=0,q=0,u=[],m=m[l]();if(null===m||b!==e.length){var m=Math.max(b,q),C=m<e.length?e.charAt(m):null,z=B();throw new this.a(A(u),C,m,z.c,z.b);}return m},toSource:function(){return this.d},a:function(e,l,h,n,p){this.name="SyntaxError";switch(e.length){case 0:e="end of input";break;case 1:e=e[0];break;default:e=e.slice(0,e.length-1).join(", ")+" or "+e[e.length-1]}l=l?y(l):"end of input";this.message="Expected "+e+
" but "+l+" found.";this.offset=h;this.c=n;this.b=p}};n.a.prototype=Error.prototype;return n}();
function nRange(r,c,h,w,table){this.row=r;this.col=c;this.rowsize=h;this.colsize=w;this.table=table;this.setValue=function(val){this.forEach(function(c){c.setValue(val)})}.bind(this);this.setDOMProperties=function(prop,value){this.forEach(function(c){var i,obj;obj=c;for(i=0;i<prop.length-1;i++)obj=obj[prop[i]];obj[prop[prop.length-1]]=value})}.bind(this);this.merge=function(){var basecell=this.table.getCell(this.row,this.column);basecell.merge(this.rowsize,this.colsize)}.bind(this);this.unmerge=function(){this.forEach(function(c){c.unmerge()})}.bind(this);
this.forEach=function(f){var rr,cc;for(rr=this.row;rr<this.row+this.rowsize;rr++)for(cc=this.col;cc<this.col+this.colsize;cc++)f(this.table.getCell(rr,cc))}}var DOMTools=function(exp){var exports=exp||{};var uniqueId=0;exports.getUniqueId=function(prefix){return(prefix||"id")+((new Date).getTime()+uniqueId++).toString(34)};return exports}(DOMTools);
var DOMTools=function(exp){var exports=exp||{};exports.scrobble=function(dom,addTo){var elems=dom.querySelectorAll("[id]");var results=addTo||{};var i;for(i=0;i<elems.length;i++)results[elems[i].id]=elems[i];return results};return exports}(DOMTools);console.log("run");data_AS3600Variables=nConvertTo2Taffy(data_AS3600Variables);
function nConvertTo2Taffy(spreadsheet){var prettyheader=spreadsheet.prettyheader;var header=spreadsheet.header;var data=spreadsheet.data;console.log(spreadsheet);var tmpobj,arr=[];for(var j,i=0;i<data.length;i++){tmpobj={};for(j=0;j<header.length;j++)tmpobj[header[j]]=data[i][j];arr.push(tmpobj)}var result=TAFFY(arr);return result}
function nCell(tbl,r,c){this.row=r;this.column=c;this.obscured=false;this.getValue=function(){return this.value}.bind(this);this.setValue=function(newval){this.value=newval;if(newval===""||newval===" ")newval="&nbsp;";this.dom.innerHTML=newval;return this}.bind(this);this.setValues=function(arr){var rows=arr.length;var columns=arr[0].length;var r,c,tmpcell;for(r=0;r<rows;r++)for(c=0;c<columns;c++){tmpcell=this.table.getCell(this.row+r,this.column+c);if(tmpcell!=undefined)tmpcell.setValue(arr[r][c])}return this}.bind(this);
this.setStyles=function(stylename,arr){var rows=arr.length;var columns=arr[0].length;var r,c,tmpcell;for(r=0;r<rows;r++)for(c=0;c<columns;c++){tmpcell=this.table.getCell(this.row+r,this.column+c);if(tmpcell!=undefined)tmpcell.dom.style[stylename]=arr[r][c]}return this}.bind(this);this.setDomProperties=function(property,arr){var rows=arr.length;var columns=arr[0].length;var r,c,tmpcell;for(r=0;r<rows;r++)for(c=0;c<columns;c++){tmpcell=this.table.getCell(this.row+r,this.column+c);if(tmpcell!=undefined)tmpcell.dom[property]=
arr[r][c]}return this}.bind(this);this.merge=function(h,w){if(w<=0||h<=0){throw new Error("Merge function must have positive non-zero integers");return}if(this.obscured==true){throw new Error("Cannot merge obscured cell");return}w=Math.min(w,this.table.getWidth()-this.column);h=Math.min(h,this.table.getHeight()-this.row);this.unmerge();var i,j;for(j=this.row;j<h+this.row;j++)for(i=this.column;i<w+this.column;i++)if(this.row==j&&this.column==i)continue;else this.table.getCell(j,i).obscured=true;this.dom.rowSpan=
h;this.dom.colSpan=w;this.table.renderTable();return this}.bind(this);this.unmerge=function(){if(this.obscured==true){throw new Error("Cannot unmerge obscured cell");return}var i,j;var w=this.dom.colSpan;var h=this.dom.rowSpan;for(j=this.row;j<h+this.row;j++)for(i=this.column;i<w+this.column;i++)if(this.row==j&&this.column==i)continue;else this.table.getCell(j,i).obscured=false;this.dom.rowSpan=1;this.dom.colSpan=1;this.table.renderTable();return this}.bind(this);this.convertToInput=function(){this.dom.innerHTML=
"";var input=document.createElement("input");input.type="text";input.value=this.value;var inputChange=function(){this.value=input.value}.bind(this);input.addEventListener("keyup",inputChange);input.addEventListener("change",inputChange);this.setValue=function(newval){input.value=newval;this.value=newval;return this}.bind(this);this.getValue=function(newval){this.value=input.value;return this.value}.bind(this);this.dom.appendChild(input);return this}.bind(this);this.convertToCheckbox=function(){this.dom.innerHTML=
"";var input=document.createElement("input");input.type="checkbox";input.checked=this.value;var inputChange=function(){this.value=input.checked}.bind(this);input.addEventListener("keyup",inputChange);input.addEventListener("change",inputChange);this.setValue=function(newval){input.checked=newval;this.value=newval;return this}.bind(this);this.getValue=function(newval){this.value=input.checked;return this.value}.bind(this);this.dom.appendChild(input);return this}.bind(this);this.convertToRadio=function(name){this.dom.innerHTML=
"";var input=document.createElement("input");input.type="radio";input.name=name;input.checked=this.value;var inputChange=function(){this.value=input.checked}.bind(this);input.addEventListener("keyup",inputChange);input.addEventListener("change",inputChange);this.setValue=function(newval){input.checked=newval;this.value=newval;return this}.bind(this);this.getValue=function(newval){this.value=input.checked;return this.value}.bind(this);this.dom.appendChild(input);return this}.bind(this);this.convertToMathJax=
function(){this.dom.innerHTML="";this.dom.id=DOMTools.getUniqueId();this.setValue=function(newval){this.dom.innerHTML="$${"+newval+"}$$";this.value=newval;return this}.bind(this);this.getValue=function(newval){return this.value}.bind(this);this.setValue(this.value);return this}.bind(this);this.getLeft=function(){return this.table.getCell(this.row,this.column-1)}.bind(this);this.getRight=function(){return this.table.getCell(this.row,this.column+1)}.bind(this);this.getUp=function(){return this.table.getCell(this.row-
1,this.column)}.bind(this);this.getDown=function(){return this.table.getCell(this.row+1,this.column)}.bind(this);this.table=tbl;this.value="";this.dom=document.createElement("td");this.setValue("")}
function nTable(r,c){this.getCell=function(r,c){try{return this.cells[r][c]}catch(e){return undefined}}.bind(this);this.getRange=function(r,c,h,w){return new nRange(r,c,h,w,this)}.bind(this);this.init=function(r,c){this.cells=[];var i,j,tmparr,tmpcell;for(j=0;j<r;j++){tmparr=[];for(i=0;i<c;i++){tmpcell=new nCell(this,j,i);tmparr.push(tmpcell)}this.cells.push(tmparr)}this.renderTable()}.bind(this);this.renderTable=function(){var i,j,tmprow;this.dom.innerHTML="";for(j=0;j<this.cells.length;j++){tmprow=
document.createElement("tr");for(i=0;i<this.cells[j].length;i++)if(this.cells[j][i].obscured==false)tmprow.appendChild(this.cells[j][i].dom);this.dom.appendChild(tmprow)}}.bind(this);this.getWidth=function(){return this.cells[0].length}.bind(this);this.getHeight=function(){return this.cells.length}.bind(this);this.cells=[];this.dom=document.createElement("table");this.dom.className="nTable";this.init(r,c)}var tab=new nTable(10,2);var asstab=new nTable(1,1);ui=DOMTools.scrobble(document.body);ui.tab3.appendChild(tab.dom);
ui.leftbarcontent.appendChild(asstab.dom);var dat=data_AS3600Variables;var arim=new Arimsys(dat);rendertables(["name","notation","value","unit"]);
function rendertables(headings){tab.init(dat().count()+1,headings.length);var cell=tab.getCell(0,0).setValues([headings]);do{cell.dom.className="heading";cell=cell.getRight()}while(cell!=undefined);cell=tab.getCell(1,1);do{cell.convertToMathJax();cell=cell.getDown()}while(cell);var x=0;var y=1;dat().order("name").each(function(r){headings.forEach(function(heading){tab.getCell(y,x).setValue(r[heading]).dom.title=r["description"];x++});x=0;y++});var av=arim.getAvaliable();console.log(av);asstab.init(av.length+
1,2);asstab.getCell(0,0).merge(1,2).setValue("Possible to Find:").dom.className="heading";cell=asstab.getCell(1,0);var butcell,butt;var i=0;do{cell.setValue(dat({"id":av[i]}).first().notation).convertToMathJax();butt=document.createElement("button");butt.innerHTML="calculate it";butt.vid=av[i];butt.onclick=function(){dat({"id":this.vid}).first().value="###";rendertables(["name","notation","value","unit"])}.bind(butt);butcell=cell.getRight();butcell.dom.appendChild(butt);i++;cell=cell.getDown()}while(cell);
MathJax.Hub.Queue(["Typeset",MathJax.Hub,document.body])}"use strict";var mainview=new Mainview(document.body);var calcblock=new Calcview;mainview.ui.tab0.appendChild(calcblock.dom);
function Calcview(){this.dom=document.createElement("div");this.dom.className="calcblock";this.topbar=document.createElement("div");this.dom.appendChild(this.topbar);this.topbar.className="calcblocktopbar selected";this.topbar.appendChild(document.createTextNode("Geometry"));this.content=document.createElement("div");this.dom.appendChild(this.content);this.content.className="calcblockcontent";this.tab=new nTable(10,3);this.content.appendChild(this.tab.dom);this.tab.getCell(0,0).merge(4,1).setValue("Known Dimentions").dom.className=
"heading";this.tab.getCell(0,1).setValue("Full geometry known");this.tab.getCell(0,2).convertToRadio("aaa");this.tab.getCell(1,1).setValue("Web breadth known");this.tab.getCell(1,2).convertToRadio("aaa");this.tab.getCell(2,1).setValue("Total depth known");this.tab.getCell(2,2).convertToRadio("aaa");this.tab.getCell(3,1).setValue("Breadth/depth ratio known");this.tab.getCell(3,2).convertToRadio("aaa");this.tab.getCell(4,0).merge(1,Infinity);this.tab.getCell(5,0).merge(3,1).setValue("Shape").dom.className=
"heading";this.tab.getCell(5,1).setValue("T/L Beam");this.tab.getCell(5,2).convertToRadio("bbb");this.tab.getCell(6,1).setValue("Rectangular");this.tab.getCell(6,2).convertToRadio("bbb");this.tab.getCell(7,1).setValue("Free-form");this.tab.getCell(7,2).convertToRadio("bbb")}
function Mainview(dom){this.dom=dom;this.ui={};this.init=function(){this.ui=DOMTools.scrobble(dom);this.ui.tabbut0.onmousedown=this.changeTab;this.ui.tabbut1.onmousedown=this.changeTab;this.ui.tabbut2.onmousedown=this.changeTab;this.ui.tabbut3.onmousedown=this.changeTab}.bind(this);this.changeTab=function(e){console.log(e.target.id);this.ui.tabbut0.className="maintab";this.ui.tabbut1.className="maintab";this.ui.tabbut2.className="maintab";this.ui.tabbut3.className="maintab";this.ui.tab0.style.display=
"none";this.ui.tab1.style.display="none";this.ui.tab2.style.display="none";this.ui.tab3.style.display="none";e.target.className+=" selected";switch(e.target.id){case "tabbut0":this.ui.tab0.style.display="block";break;case "tabbut1":this.ui.tab1.style.display="block";break;case "tabbut2":this.ui.tab2.style.display="block";break;case "tabbut3":this.ui.tab3.style.display="block";break}}.bind(this);this.init()};