function EventDispatcher() { !0 != this.isEventDispatcher && (this.isEventDispatcher = !0, this.events = {}, this.on = function (a, d) { "string" !== typeof a || "function" !== typeof d ? console.log("Invalid event registration, " + a) : (void 0 === this.events[a] && (this.events[a] = []), this.events[a].push(d)) }.bind(this), this.clearListeners = function (a) { void 0 !== this.events[a] && (this.events[a] = []) }.bind(this), this.dispatch = function (a, d) { if (void 0 !== this.events[a]) for (var b = 0; b < this.events[a].length; b++) this.events[a][b](d) }.bind(this)) }
var DOMTools = function (a) { a = a || {}; a.scrobble = function (a, b) { var e = a.querySelectorAll("[id]"), f = b || {}, c; for (c = 0; c < e.length; c++) f[e[c].id] = e[c]; return f }; return a }(DOMTools); "use strict"; var ui = DOMTools.scrobble(document.body); ui.tabbut0.onmousedown = this.changeTab; ui.tabbut1.onmousedown = this.changeTab; ui.tabbut2.onmousedown = this.changeTab; ui.tabbut3.onmousedown = this.changeTab;
function changeTab(a) {
	ui.tabbut0.className = "maintab"; ui.tabbut1.className = "maintab"; ui.tabbut2.className = "maintab"; ui.tabbut3.className = "maintab"; ui.tab0.style.display = "none"; ui.tab1.style.display = "none"; ui.tab2.style.display = "none"; ui.tab3.style.display = "none"; a.target.className += " selected"; switch (a.target.id) {
		case "tabbut0": ui.tab0.style.display = "block"; break; case "tabbut1": ui.tab1.style.display = "block"; break; case "tabbut2": ui.tab2.style.display = "block"; break; case "tabbut3": ui.tab3.style.display =
		"block"
	}
} var cbDI = new cbDesignIntent, cbEC = new cbExposureClassifictaion, cbCS = new cbConcreteStrength, cbBS = new cbBeamShape; ui.tab0.appendChild(cbDI.dom); ui.tab0.appendChild(cbEC.dom); ui.tab0.appendChild(cbCS.dom); ui.tab0.appendChild(cbBS.dom);
function cbDesignIntent() { CalcBlock.call(this); this.setTitle("Design Intent"); this.fram = document.createElement("iframe"); this.fram.src = "partials/test.html"; this.dom_content.appendChild(this.fram); this.fram.loaded = function () { console.log("nerp"); null != this.fram.contentDocument ? this.dom_content.innerHTML = this.fram.contentDocument.body.innerHTML : window.setTimeout(this.fram.loaded, 1E3) }.bind(this); this.fram.loaded() }
function cbExposureClassifictaion() { CalcBlock.call(this); this.setTitle("Exposure Classification") } function cbConcreteStrength() { CalcBlock.call(this); this.setTitle("Concrete Strength") } function cbBeamShape() { CalcBlock.call(this); this.setTitle("Beam Shape") }
function CalcBlock() {
	EventDispatcher.call(this); this._title = "untitled"; this.dom_minimizebutton = document.createElement("div"); this.dom_minimizebutton.className = "minbut"; this.dom_closebutton = document.createElement("div"); this.dom_closebutton.className = "closebut"; this.dom_titlebar = document.createElement("div"); this.dom_titlebar.className = "titlebar selected"; this.dom_titlebar.appendChild(this.dom_closebutton); this.dom_titlebar.appendChild(this.dom_minimizebutton); this.dom_titletext = document.createElement("div");
	this.dom_titletext.className = "titletext"; this.dom_titlebar.appendChild(this.dom_titletext); this.dom_content = document.createElement("div"); this.dom_content.className = "content"; this.dom_content.style.display = "block"; this.dom = document.createElement("div"); this.dom.className = "calcblock"; this.dom.appendChild(this.dom_titlebar); this.dom.appendChild(this.dom_content); this.setTitle = function (a) { this._title = a; this.dom_titletext.innerHTML = a }.bind(this); this.dom_minimizebutton.addEventListener("mousedown", function (a) {
		"block" ===
		this.dom_content.style.display ? (this.dom_content.style.display = "none", this.dom_titlebar.className = "titlebar", this.dispatch("minimise", a)) : (this.dom_content.style.display = "block", this.dom_titlebar.className = "titlebar selected", this.dispatch("maximise", a))
	}.bind(this)); this.dom_closebutton.addEventListener("mousedown", function (a) { this.dispatch("close", a) }.bind(this))
};